using Paster.Windows.Services;
using Windows.Foundation;
using Windows.Graphics.Imaging;
using Windows.Storage.Streams;

namespace Paster.Windows.Utilities;

/// <summary>
/// Image scaling for clipboard storage, mirroring Paster/Utilities/ImageUtils.swift
/// (compressedForStorage / thumbnailPNG). Images are stored at most
/// <see cref="StorageMaxDimension"/> on the long edge and previewed from a small
/// thumbnail, so a 4K screenshot no longer costs tens of megabytes per capture.
/// </summary>
public static class ImageUtils
{
    public const uint StorageMaxDimension = 1600;
    public const uint ThumbnailMaxDimension = 240;

    /// <summary>
    /// Thumbnails are JPEG: a 240px JPEG is a few tens of KB where the same PNG runs to a few
    /// hundred, and the history query loads every thumbnail on each search keystroke. They are
    /// previews only, so losing transparency (flattened onto white) is acceptable.
    /// </summary>
    public const float ThumbnailJpegQuality = 0.8f;

    /// <summary>
    /// Thumbnails larger than this were written by older builds (PNG, or Retina-sized copies)
    /// and are regenerated by <see cref="ImageStorageMigration"/>. A 240px JPEG never reaches it.
    /// </summary>
    public const int OversizedThumbnailBytes = 100 * 1024;

    /// <summary>
    /// Scales an image down for persistence. Images already within the limit are returned
    /// untouched; images are never upscaled.
    /// </summary>
    public static Task<byte[]> CompressForStorageAsync(byte[] bytes, uint maxDimension = StorageMaxDimension) =>
        ResizeAsync(bytes, maxDimension, "storage compression");

    /// <summary>
    /// Produces a small JPEG preview used by the history cards. Always re-encodes, so even an
    /// original that is already within the size limit yields a compact thumbnail.
    /// </summary>
    public static Task<byte[]> CreateThumbnailAsync(byte[] bytes, uint maxDimension = ThumbnailMaxDimension) =>
        ResizeAsync(bytes, maxDimension, "thumbnail generation", BitmapEncoder.JpegEncoderId, alwaysEncode: true);

    private static async Task<byte[]> ResizeAsync(byte[] bytes, uint maxDimension, string operation,
        Guid? encoderId = null, bool alwaysEncode = false)
    {
        if (bytes.Length == 0 || maxDimension == 0)
        {
            return bytes;
        }

        try
        {
            using var source = await ToStreamAsync(bytes);
            var decoder = await BitmapDecoder.CreateAsync(source);
            var width = decoder.PixelWidth;
            var height = decoder.PixelHeight;
            if (width == 0 || height == 0)
            {
                return bytes;
            }

            var longest = Math.Max(width, height);
            if (longest <= maxDimension && !alwaysEncode)
            {
                return bytes;
            }

            var scale = Math.Min(1.0, (double)maxDimension / longest);
            var targetWidth = Math.Max(1u, (uint)Math.Floor(width * scale));
            var targetHeight = Math.Max(1u, (uint)Math.Floor(height * scale));

            var pixels = await decoder.GetPixelDataAsync(
                BitmapPixelFormat.Bgra8,
                BitmapAlphaMode.Straight,
                new BitmapTransform
                {
                    ScaledWidth = targetWidth,
                    ScaledHeight = targetHeight,
                    InterpolationMode = BitmapInterpolationMode.Fant
                },
                ExifOrientationMode.RespectExifOrientation,
                ColorManagementMode.DoNotColorManage);

            var pixelBytes = pixels.DetachPixelData();
            var jpeg = encoderId == BitmapEncoder.JpegEncoderId;
            if (jpeg)
            {
                FlattenOntoWhite(pixelBytes);
            }

            using var target = new InMemoryRandomAccessStream();
            var encoder = jpeg
                ? await BitmapEncoder.CreateAsync(BitmapEncoder.JpegEncoderId, target, new BitmapPropertySet
                {
                    ["ImageQuality"] = new BitmapTypedValue(ThumbnailJpegQuality, PropertyType.Single)
                })
                : await BitmapEncoder.CreateAsync(encoderId ?? BitmapEncoder.PngEncoderId, target);
            encoder.SetPixelData(
                BitmapPixelFormat.Bgra8,
                jpeg ? BitmapAlphaMode.Ignore : BitmapAlphaMode.Straight,
                targetWidth,
                targetHeight,
                decoder.DpiX <= 0 ? 96 : decoder.DpiX,
                decoder.DpiY <= 0 ? 96 : decoder.DpiY,
                pixelBytes);
            await encoder.FlushAsync();

            return await ToBytesAsync(target);
        }
        catch (Exception ex)
        {
            // An undecodable clipboard image must still be captured, just without downscaling.
            AppLog.Error($"Image {operation} failed; keeping the original bytes.", ex);
            return bytes;
        }
    }

    /// <summary>
    /// JPEG has no alpha channel; composite straight-alpha BGRA onto white so transparent
    /// regions of a screenshot come out white rather than black.
    /// </summary>
    private static void FlattenOntoWhite(byte[] bgra)
    {
        for (var i = 0; i + 3 < bgra.Length; i += 4)
        {
            var alpha = bgra[i + 3];
            if (alpha == 255)
            {
                continue;
            }

            var inverse = 255 - alpha;
            bgra[i] = (byte)((bgra[i] * alpha + 255 * inverse) / 255);
            bgra[i + 1] = (byte)((bgra[i + 1] * alpha + 255 * inverse) / 255);
            bgra[i + 2] = (byte)((bgra[i + 2] * alpha + 255 * inverse) / 255);
            bgra[i + 3] = 255;
        }
    }

    private static async Task<InMemoryRandomAccessStream> ToStreamAsync(byte[] bytes)
    {
        var stream = new InMemoryRandomAccessStream();
        using (var writer = new DataWriter(stream))
        {
            writer.WriteBytes(bytes);
            await writer.StoreAsync();
            await writer.FlushAsync();
            writer.DetachStream();
        }

        stream.Seek(0);
        return stream;
    }

    private static async Task<byte[]> ToBytesAsync(IRandomAccessStream stream)
    {
        var length = checked((int)stream.Size);
        var bytes = new byte[length];
        using var reader = new DataReader(stream.GetInputStreamAt(0));
        await reader.LoadAsync((uint)length);
        reader.ReadBytes(bytes);
        return bytes;
    }
}
